export interface RichestFootballerEntry {
  rank: number;
  name: string;
  age: number;
  nationality: string;
  countryCode: string;
  countryOfClub: string;
  countryOfClubCode: string;
  club: string;
  position: string;
  netWorth: number;
  netWorthDisplay: string;
  annualSalary: string;
  primarySource: string;
  previousRank: number;
  rankChange: 'up' | 'down' | 'same';
  image: string;
}

const RICHEST_FOOTBALLERS: RichestFootballerEntry[] = [
  {
    rank: 1,
    name: 'Cristiano Ronaldo',
    age: 40,
    nationality: 'Portuguese',
    countryCode: 'pt',
    countryOfClub: 'Saudi Arabia',
    countryOfClubCode: 'sa',
    club: 'Al-Nassr',
    position: 'Forward',
    netWorth: 1200,
    netWorthDisplay: '$1.2 – $1.4B',
    annualSalary: '$235M',
    primarySource: 'Salary & Endorsements',
    previousRank: 1,
    rankChange: 'same',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Cristiano_Ronaldo_2275_%28cropped%29.jpg/960px-Cristiano_Ronaldo_2275_%28cropped%29.jpg',
  },
  {
    rank: 2,
    name: 'Lionel Messi',
    age: 38,
    nationality: 'Argentine',
    countryCode: 'ar',
    countryOfClub: 'United States',
    countryOfClubCode: 'us',
    club: 'Inter Miami',
    position: 'Forward',
    netWorth: 1000,
    netWorthDisplay: '$1.0 – $1.1B',
    annualSalary: '$70M',
    primarySource: 'Salary & Endorsements',
    previousRank: 2,
    rankChange: 'same',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg/960px-Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg',
  },
  {
    rank: 3,
    name: 'Neymar Jr',
    age: 33,
    nationality: 'Brazilian',
    countryCode: 'br',
    countryOfClub: 'Saudi Arabia',
    countryOfClubCode: 'sa',
    club: 'Al-Hilal',
    position: 'Forward',
    netWorth: 450,
    netWorthDisplay: '$450M',
    annualSalary: '$80M',
    primarySource: 'Salary & Endorsements',
    previousRank: 3,
    rankChange: 'same',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg/960px-Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg',
  },
  {
    rank: 4,
    name: 'Kylian Mbappé',
    age: 27,
    nationality: 'French',
    countryCode: 'fr',
    countryOfClub: 'Spain',
    countryOfClubCode: 'es',
    club: 'Real Madrid',
    position: 'Forward',
    netWorth: 250,
    netWorthDisplay: '$250M',
    annualSalary: '$70M',
    primarySource: 'Salary & Endorsements',
    previousRank: 4,
    rankChange: 'same',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg/960px-Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg',
  },
  {
    rank: 5,
    name: 'Karim Benzema',
    age: 38,
    nationality: 'French',
    countryCode: 'fr',
    countryOfClub: 'Saudi Arabia',
    countryOfClubCode: 'sa',
    club: 'Al-Ittihad',
    position: 'Forward',
    netWorth: 200,
    netWorthDisplay: '$200M',
    annualSalary: '$100M',
    primarySource: 'Salary & Endorsements',
    previousRank: 7,
    rankChange: 'up',
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Karim_Benzema_Pick.jpg',
  },
  {
    rank: 6,
    name: 'Harry Kane',
    age: 32,
    nationality: 'English',
    countryCode: 'gb-eng',
    countryOfClub: 'Germany',
    countryOfClubCode: 'de',
    club: 'Bayern Munich',
    position: 'Forward',
    netWorth: 140,
    netWorthDisplay: '$140M',
    annualSalary: '$25M',
    primarySource: 'Salary & Endorsements',
    previousRank: 9,
    rankChange: 'up',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Harry_Kane_England_v_Ghana_23_June_2026-219_%28cropped%29.jpg/960px-Harry_Kane_England_v_Ghana_23_June_2026-219_%28cropped%29.jpg',
  },
  {
    rank: 7,
    name: 'Mohamed Salah',
    age: 33,
    nationality: 'Egyptian',
    countryCode: 'eg',
    countryOfClub: 'United Kingdom',
    countryOfClubCode: 'gb',
    club: 'Liverpool',
    position: 'Forward',
    netWorth: 140,
    netWorthDisplay: '$140M',
    annualSalary: '$35M',
    primarySource: 'Salary & Endorsements',
    previousRank: 8,
    rankChange: 'up',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Mohamed_Salah_2018.jpg',
  },
  {
    rank: 8,
    name: 'Kevin De Bruyne',
    age: 34,
    nationality: 'Belgian',
    countryCode: 'be',
    countryOfClub: 'United Kingdom',
    countryOfClubCode: 'gb',
    club: 'Manchester City',
    position: 'Midfielder',
    netWorth: 130,
    netWorthDisplay: '$130M',
    annualSalary: '$25M',
    primarySource: 'Salary & Endorsements',
    previousRank: 6,
    rankChange: 'down',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/960px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg',
  },
  {
    rank: 9,
    name: 'Erling Haaland',
    age: 25,
    nationality: 'Norwegian',
    countryCode: 'no',
    countryOfClub: 'United Kingdom',
    countryOfClubCode: 'gb',
    club: 'Manchester City',
    position: 'Forward',
    netWorth: 100,
    netWorthDisplay: '$100M',
    annualSalary: '$60M',
    primarySource: 'Salary & Endorsements',
    previousRank: 5,
    rankChange: 'down',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg/960px-Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg',
  },
  {
    rank: 10,
    name: 'Sadio Mané',
    age: 34,
    nationality: 'Senegalese',
    countryCode: 'sn',
    countryOfClub: 'Saudi Arabia',
    countryOfClubCode: 'sa',
    club: 'Al-Nassr',
    position: 'Forward',
    netWorth: 100,
    netWorthDisplay: '$100M',
    annualSalary: '$40M',
    primarySource: 'Salary & Endorsements',
    previousRank: 10,
    rankChange: 'same',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Sadio_Mane_France_v_Senegal_16_June_2026-450.jpg/960px-Sadio_Mane_France_v_Senegal_16_June_2026-450.jpg',
  },
];

export async function getRichestFootballers(): Promise<RichestFootballerEntry[]> {
  return RICHEST_FOOTBALLERS;
}
