import type { CricketMatchRaw } from './cricketApi';

const fixtures: CricketMatchRaw[] = [
  // === July 15 ===
  {
    id: 'fixture-zim-vs-ban-1st-t20i-2026-07-15',
    homeTeam: 'Zimbabwe',
    awayTeam: 'Bangladesh',
    date: '2026-07-15T10:30:00Z',
    venue: 'Queens Sports Club, Bulawayo',
    series: 'Bangladesh tour of Zimbabwe, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Zimbabwe vs Bangladesh, 1st T20I',
  },
  // === July 16 ===
  {
    id: 'fixture-eng-vs-ind-2nd-odi-2026-07-16',
    homeTeam: 'England',
    awayTeam: 'India',
    date: '2026-07-16T12:00:00Z',
    venue: 'Sophia Gardens, Cardiff',
    series: 'India tour of England, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'England vs India, 2nd ODI',
  },
  // === July 17 ===
  {
    id: 'fixture-wi-vs-nz-3rd-odi-2026-07-17',
    homeTeam: 'West Indies',
    awayTeam: 'New Zealand',
    date: '2026-07-17T00:30:00Z',
    venue: 'Providence Stadium, Guyana',
    series: 'New Zealand tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies vs New Zealand, 3rd ODI',
  },
  {
    id: 'fixture-zim-vs-ban-2nd-t20i-2026-07-17',
    homeTeam: 'Zimbabwe',
    awayTeam: 'Bangladesh',
    date: '2026-07-17T10:30:00Z',
    venue: 'Queens Sports Club, Bulawayo',
    series: 'Bangladesh tour of Zimbabwe, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Zimbabwe vs Bangladesh, 2nd T20I',
  },
  // === July 18 ===
  {
    id: 'fixture-wi-select-xi-vs-pak-warmup-day1-2026-07-18',
    homeTeam: 'West Indies Select XI',
    awayTeam: 'Pakistan',
    date: '2026-07-18T14:00:00Z',
    venue: 'Brian Lara Stadium, Tarouba, Trinidad',
    series: 'Pakistan tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies Select XI vs Pakistan, 4-Day Warm-up match, Day 1',
  },
  // === July 19 ===
  {
    id: 'fixture-eng-vs-ind-3rd-odi-2026-07-19',
    homeTeam: 'England',
    awayTeam: 'India',
    date: '2026-07-19T10:00:00Z',
    venue: "Lord's, London",
    series: 'India tour of England, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'England vs India, 3rd ODI',
  },
  {
    id: 'fixture-zim-vs-ban-3rd-t20i-2026-07-19',
    homeTeam: 'Zimbabwe',
    awayTeam: 'Bangladesh',
    date: '2026-07-19T10:30:00Z',
    venue: 'Queens Sports Club, Bulawayo',
    series: 'Bangladesh tour of Zimbabwe, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Zimbabwe vs Bangladesh, 3rd T20I',
  },
  {
    id: 'fixture-wi-select-xi-vs-pak-warmup-day2-2026-07-19',
    homeTeam: 'West Indies Select XI',
    awayTeam: 'Pakistan',
    date: '2026-07-19T14:00:00Z',
    venue: 'Brian Lara Stadium, Tarouba, Trinidad',
    series: 'Pakistan tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies Select XI vs Pakistan, 4-Day Warm-up match, Day 2',
  },
  {
    id: 'fixture-wi-vs-nz-4th-odi-2026-07-19',
    homeTeam: 'West Indies',
    awayTeam: 'New Zealand',
    date: '2026-07-19T14:00:00Z',
    venue: 'Kensington Oval, Bridgetown, Barbados',
    series: 'New Zealand tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies vs New Zealand, 4th ODI',
  },
  // === July 20 ===
  {
    id: 'fixture-wi-select-xi-vs-pak-warmup-day3-2026-07-20',
    homeTeam: 'West Indies Select XI',
    awayTeam: 'Pakistan',
    date: '2026-07-20T14:00:00Z',
    venue: 'Brian Lara Stadium, Tarouba, Trinidad',
    series: 'Pakistan tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies Select XI vs Pakistan, 4-Day Warm-up match, Day 3',
  },
  // === July 21 ===
  {
    id: 'fixture-nep-vs-nam-116th-cwc-l2-2026-07-21',
    homeTeam: 'Nepal',
    awayTeam: 'Namibia',
    date: '2026-07-21T09:00:00Z',
    venue: 'Sportpark Maarschalkerweerd, Utrecht',
    series: 'ICC Cricket World Cup League Two 2023-27',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Nepal vs Namibia, 116th Match',
  },
  {
    id: 'fixture-wi-select-xi-vs-pak-warmup-day4-2026-07-21',
    homeTeam: 'West Indies Select XI',
    awayTeam: 'Pakistan',
    date: '2026-07-21T14:00:00Z',
    venue: 'Brian Lara Stadium, Tarouba, Trinidad',
    series: 'Pakistan tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies Select XI vs Pakistan, 4-Day Warm-up match, Day 4',
  },
  // === July 22 ===
  {
    id: 'fixture-wi-vs-nz-5th-odi-2026-07-22',
    homeTeam: 'West Indies',
    awayTeam: 'New Zealand',
    date: '2026-07-22T00:30:00Z',
    venue: 'Kensington Oval, Bridgetown, Barbados',
    series: 'New Zealand tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies vs New Zealand, 5th ODI',
  },
  {
    id: 'fixture-eng-vs-ind-1st-t20i-2026-07-22',
    homeTeam: 'England',
    awayTeam: 'India',
    date: '2026-07-22T17:30:00Z',
    venue: 'Edgbaston, Birmingham',
    series: 'India tour of England, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'England vs India, 1st T20I',
  },
  {
    id: 'fixture-zim-vs-ban-1st-odi-2026-07-22',
    homeTeam: 'Zimbabwe',
    awayTeam: 'Bangladesh',
    date: '2026-07-22T09:00:00Z',
    venue: 'Harare Sports Club, Harare',
    series: 'Bangladesh tour of Zimbabwe, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Zimbabwe vs Bangladesh, 1st ODI',
  },
  {
    id: 'fixture-ned-vs-sco-cwc-l2-2026-07-22',
    homeTeam: 'Netherlands',
    awayTeam: 'Scotland',
    date: '2026-07-22T11:00:00Z',
    venue: 'Sportpark Maarschalkerweerd, Utrecht',
    series: 'ICC Cricket World Cup League Two 2023-27',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Netherlands vs Scotland, 117th Match',
  },
  // === July 23 ===
  {
    id: 'fixture-ned-vs-nep-117th-cwc-l2-2026-07-23',
    homeTeam: 'Netherlands',
    awayTeam: 'Nepal',
    date: '2026-07-23',
    venue: 'Sportpark Maarschalkerweerd, Utrecht',
    series: 'ICC Cricket World Cup League Two 2023-27',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Netherlands vs Nepal, 117th Match',
  },
  // === July 24 ===
  {
    id: 'fixture-eng-vs-ind-2nd-t20i-2026-07-24',
    homeTeam: 'England',
    awayTeam: 'India',
    date: '2026-07-24T17:30:00Z',
    venue: 'The Oval, London',
    series: 'India tour of England, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'England vs India, 2nd T20I',
  },
  {
    id: 'fixture-zim-vs-ban-2nd-odi-2026-07-24',
    homeTeam: 'Zimbabwe',
    awayTeam: 'Bangladesh',
    date: '2026-07-24T09:00:00Z',
    venue: 'Queens Sports Club, Bulawayo',
    series: 'Bangladesh tour of Zimbabwe, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Zimbabwe vs Bangladesh, 2nd ODI',
  },
  {
    id: 'fixture-sco-vs-nam-cwc-l2-2026-07-24',
    homeTeam: 'Scotland',
    awayTeam: 'Namibia',
    date: '2026-07-24T11:00:00Z',
    venue: 'Sportpark Maarschalkerweerd, Utrecht',
    series: 'ICC Cricket World Cup League Two 2023-27',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Scotland vs Namibia, 118th Match',
  },
  // === July 25 ===
  {
    id: 'fixture-wi-vs-nz-1st-t20i-2026-07-25',
    homeTeam: 'West Indies',
    awayTeam: 'New Zealand',
    date: '2026-07-25T00:30:00Z',
    venue: 'Kensington Oval, Bridgetown, Barbados',
    series: 'New Zealand tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies vs New Zealand, 1st T20I',
  },
  {
    id: 'fixture-man-orig-vs-lon-spirit-hundred-2026-07-25',
    homeTeam: 'Manchester Originals',
    awayTeam: 'London Spirit',
    date: '2026-07-25T18:00:00Z',
    venue: 'Old Trafford, Manchester',
    series: 'The Hundred Men, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Manchester Originals vs London Spirit, Match 1',
  },
  {
    id: 'fixture-pak-vs-wi-select-test-2026-07-25',
    homeTeam: 'Pakistan',
    awayTeam: 'West Indies',
    date: '2026-07-25T10:00:00Z',
    venue: 'Sabina Park, Kingston, Jamaica',
    series: 'Pakistan tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Pakistan vs West Indies, 1st Test, Day 1',
  },
  // === July 26 ===
  {
    id: 'fixture-zim-vs-ban-3rd-odi-2026-07-26',
    homeTeam: 'Zimbabwe',
    awayTeam: 'Bangladesh',
    date: '2026-07-26T09:00:00Z',
    venue: 'Queens Sports Club, Bulawayo',
    series: 'Bangladesh tour of Zimbabwe, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Zimbabwe vs Bangladesh, 3rd ODI',
  },
  {
    id: 'fixture-trent-rok-vs-sou-brave-hundred-2026-07-26',
    homeTeam: 'Trent Rockets',
    awayTeam: 'Southern Brave',
    date: '2026-07-26T14:30:00Z',
    venue: 'Trent Bridge, Nottingham',
    series: 'The Hundred Men, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Trent Rockets vs Southern Brave, Match 2',
  },
  {
    id: 'fixture-wi-vs-nz-2nd-t20i-2026-07-26',
    homeTeam: 'West Indies',
    awayTeam: 'New Zealand',
    date: '2026-07-26T00:30:00Z',
    venue: 'Providence Stadium, Guyana',
    series: 'New Zealand tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies vs New Zealand, 2nd T20I',
  },
  // === July 27 ===
  {
    id: 'fixture-eng-vs-ind-3rd-t20i-2026-07-27',
    homeTeam: 'England',
    awayTeam: 'India',
    date: '2026-07-27T17:30:00Z',
    venue: 'Old Trafford, Manchester',
    series: 'India tour of England, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'England vs India, 3rd T20I',
  },
  {
    id: 'fixture-ned-vs-nam-cwc-l2-2026-07-27',
    homeTeam: 'Netherlands',
    awayTeam: 'Namibia',
    date: '2026-07-27T11:00:00Z',
    venue: 'Sportpark Maarschalkerweerd, Utrecht',
    series: 'ICC Cricket World Cup League Two 2023-27',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Netherlands vs Namibia, 119th Match',
  },
  {
    id: 'fixture-birm-phoenix-vs-welsh-fire-hundred-2026-07-27',
    homeTeam: 'Birmingham Phoenix',
    awayTeam: 'Welsh Fire',
    date: '2026-07-27T18:00:00Z',
    venue: 'Edgbaston, Birmingham',
    series: 'The Hundred Men, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Birmingham Phoenix vs Welsh Fire, Match 3',
  },
  // === Women's Matches ===
  // England Women tour of India (through July 18)
  {
    id: 'fixture-ind-w-vs-eng-w-2nd-odi-2026-07-16',
    homeTeam: 'India Women',
    awayTeam: 'England Women',
    date: '2026-07-16T09:00:00Z',
    venue: 'Wankhede Stadium, Mumbai',
    series: 'England Women tour of India, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'India Women vs England Women, 2nd ODI',
  },
  {
    id: 'fixture-ind-w-vs-eng-w-3rd-odi-2026-07-18',
    homeTeam: 'India Women',
    awayTeam: 'England Women',
    date: '2026-07-18T09:00:00Z',
    venue: 'Wankhede Stadium, Mumbai',
    series: 'England Women tour of India, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'India Women vs England Women, 3rd ODI',
  },
  // Zimbabwe Women vs Bangladesh Women (through July 18)
  {
    id: 'fixture-zim-w-vs-ban-w-4th-t20i-2026-07-16',
    homeTeam: 'Zimbabwe Women',
    awayTeam: 'Bangladesh Women',
    date: '2026-07-16T10:00:00Z',
    venue: 'Harare Sports Club, Harare',
    series: 'Bangladesh Women tour of Zimbabwe, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Zimbabwe Women vs Bangladesh Women, 4th T20I',
  },
  {
    id: 'fixture-zim-w-vs-ban-w-5th-t20i-2026-07-17',
    homeTeam: 'Zimbabwe Women',
    awayTeam: 'Bangladesh Women',
    date: '2026-07-17T10:00:00Z',
    venue: 'Harare Sports Club, Harare',
    series: 'Bangladesh Women tour of Zimbabwe, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Zimbabwe Women vs Bangladesh Women, 5th T20I',
  },
  {
    id: 'fixture-zim-w-vs-ban-w-1st-odi-2026-07-18',
    homeTeam: 'Zimbabwe Women',
    awayTeam: 'Bangladesh Women',
    date: '2026-07-18T10:00:00Z',
    venue: 'Harare Sports Club, Harare',
    series: 'Bangladesh Women tour of Zimbabwe, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Zimbabwe Women vs Bangladesh Women, 1st ODI',
  },
  // West Indies Women vs Pakistan Women (from July 17)
  {
    id: 'fixture-wi-w-vs-pak-w-1st-t20i-2026-07-17',
    homeTeam: 'West Indies Women',
    awayTeam: 'Pakistan Women',
    date: '2026-07-17T14:00:00Z',
    venue: 'Coolidge Cricket Ground, Antigua',
    series: 'Pakistan Women tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies Women vs Pakistan Women, 1st T20I',
  },
  {
    id: 'fixture-wi-w-vs-pak-w-2nd-t20i-2026-07-19',
    homeTeam: 'West Indies Women',
    awayTeam: 'Pakistan Women',
    date: '2026-07-19T14:00:00Z',
    venue: 'Coolidge Cricket Ground, Antigua',
    series: 'Pakistan Women tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies Women vs Pakistan Women, 2nd T20I',
  },
  {
    id: 'fixture-wi-w-vs-pak-w-3rd-t20i-2026-07-21',
    homeTeam: 'West Indies Women',
    awayTeam: 'Pakistan Women',
    date: '2026-07-21T14:00:00Z',
    venue: 'Coolidge Cricket Ground, Antigua',
    series: 'Pakistan Women tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies Women vs Pakistan Women, 3rd T20I',
  },
  {
    id: 'fixture-wi-w-vs-pak-w-1st-odi-2026-07-23',
    homeTeam: 'West Indies Women',
    awayTeam: 'Pakistan Women',
    date: '2026-07-23T14:00:00Z',
    venue: 'Coolidge Cricket Ground, Antigua',
    series: 'Pakistan Women tour of West Indies, 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'West Indies Women vs Pakistan Women, 1st ODI',
  },
  // Namibia Women's T20I Quadrangular Series (July 21-26)
  {
    id: 'fixture-nam-w-vs-uga-w-quad-1-2026-07-21',
    homeTeam: 'Namibia Women',
    awayTeam: 'Uganda Women',
    date: '2026-07-21T09:00:00Z',
    venue: 'Wanderers Cricket Ground, Windhoek',
    series: 'Women T20I Quadrangular Series (Namibia), 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Namibia Women vs Uganda Women, Match 1',
  },
  {
    id: 'fixture-hkg-w-vs-uga-w-quad-2-2026-07-21',
    homeTeam: 'Hong Kong Women',
    awayTeam: 'Uganda Women',
    date: '2026-07-21T13:00:00Z',
    venue: 'Wanderers Cricket Ground, Windhoek',
    series: 'Women T20I Quadrangular Series (Namibia), 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Hong Kong Women vs Uganda Women, Match 2',
  },
  {
    id: 'fixture-nam-w-vs-hkg-w-quad-3-2026-07-22',
    homeTeam: 'Namibia Women',
    awayTeam: 'Hong Kong Women',
    date: '2026-07-22T09:00:00Z',
    venue: 'Wanderers Cricket Ground, Windhoek',
    series: 'Women T20I Quadrangular Series (Namibia), 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Namibia Women vs Hong Kong Women, Match 3',
  },
  {
    id: 'fixture-nam-w-vs-uga-w-quad-4-2026-07-23',
    homeTeam: 'Namibia Women',
    awayTeam: 'Uganda Women',
    date: '2026-07-23T09:00:00Z',
    venue: 'Wanderers Cricket Ground, Windhoek',
    series: 'Women T20I Quadrangular Series (Namibia), 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Namibia Women vs Uganda Women, Match 4',
  },
  {
    id: 'fixture-hkg-w-vs-uga-w-quad-5-2026-07-24',
    homeTeam: 'Hong Kong Women',
    awayTeam: 'Uganda Women',
    date: '2026-07-24T09:00:00Z',
    venue: 'Wanderers Cricket Ground, Windhoek',
    series: 'Women T20I Quadrangular Series (Namibia), 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Hong Kong Women vs Uganda Women, Match 5',
  },
  {
    id: 'fixture-nam-w-vs-hkg-w-quad-6-2026-07-25',
    homeTeam: 'Namibia Women',
    awayTeam: 'Hong Kong Women',
    date: '2026-07-25T09:00:00Z',
    venue: 'Wanderers Cricket Ground, Windhoek',
    series: 'Women T20I Quadrangular Series (Namibia), 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Namibia Women vs Hong Kong Women, Match 6',
  },
  {
    id: 'fixture-nam-w-vs-hkg-w-final-2026-07-26',
    homeTeam: 'Namibia Women',
    awayTeam: 'Hong Kong Women',
    date: '2026-07-26T09:00:00Z',
    venue: 'Wanderers Cricket Ground, Windhoek',
    series: 'Women T20I Quadrangular Series (Namibia), 2026',
    status: 'upcoming',
    homeScore: '',
    awayScore: '',
    name: 'Namibia Women vs Hong Kong Women, Final',
  },
];

export function getUpcomingFixtures(): CricketMatchRaw[] {
  const today = new Date().toISOString().split('T')[0];
  return fixtures.filter((f) => {
    const matchDate = (f.date || '').split('T')[0];
    return matchDate >= today;
  });
}
